name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20
    - run: npm ci --no-audit
    - run: npm run build
    - run: npm run lint
    - run: npm test
